### ISSUE TITLE
getData() and objects

### ISSUE THREAD

**Issue by vanodevium** [mnapoli/bof#2]
For what main reason you do not support returning objects in `getData()`?
This is very useful in many situations, as for me.

**Comment by mnapoli** [comment]
Deserializing as object is less common than using arrays, which is why I went with the simplest solution.

**Comment by vanodevium** [comment]
Great! How about parameter `(bool) returnAsObject`?

**Comment by mnapoli** [comment]
I honestly prefer to keep it simple and opinionated, because any other use case can be covered by using the raw body. This is a problem I've seen a lot in my older open source projects were I added everything possible, and I want to try and avoid that in that specific project, to try to keep it as simple as possible.

**Comment by vanodevium** [comment]
Ok. Thanks!
